//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinger.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinger.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_AddConnection {
            get {
                return ResourceManager.GetString("Button_AddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Button_ChangeConnection {
            get {
                return ResourceManager.GetString("Button_ChangeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Button_RemoveConnection {
            get {
                return ResourceManager.GetString("Button_RemoveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ping.
        /// </summary>
        public static string Button_StartPing {
            get {
                return ResourceManager.GetString("Button_StartPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop ping.
        /// </summary>
        public static string Button_StopPing {
            get {
                return ResourceManager.GetString("Button_StopPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Button_Test {
            get {
                return ResourceManager.GetString("Button_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection list.
        /// </summary>
        public static string ConnectionsTab_ConnectionsList {
            get {
                return ResourceManager.GetString("ConnectionsTab_ConnectionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        public static string ConnectionsTab_InputConnection {
            get {
                return ResourceManager.GetString("ConnectionsTab_InputConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ConnectionsTable_Host {
            get {
                return ResourceManager.GetString("ConnectionsTable_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConnectionsTable_Name {
            get {
                return ResourceManager.GetString("ConnectionsTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        public static string DialogAddChangeConnection_Add {
            get {
                return ResourceManager.GetString("DialogAddChangeConnection_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change connection.
        /// </summary>
        public static string DialogAddChangeConnection_Change {
            get {
                return ResourceManager.GetString("DialogAddChangeConnection_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string DialogAddChangeConnection_Host {
            get {
                return ResourceManager.GetString("DialogAddChangeConnection_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string DialogAddChangeConnection_Name {
            get {
                return ResourceManager.GetString("DialogAddChangeConnection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string MainTab_Ping {
            get {
                return ResourceManager.GetString("MainTab_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainTab_Settings {
            get {
                return ResourceManager.GetString("MainTab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the availability of the device.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find host.
        /// </summary>
        public static string Ping_CouldNotFindHost {
            get {
                return ResourceManager.GetString("Ping_CouldNotFindHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Ping_Microseconds {
            get {
                return ResourceManager.GetString("Ping_Microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out.
        /// </summary>
        public static string Ping_RequestTimedOut {
            get {
                return ResourceManager.GetString("Ping_RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound:.
        /// </summary>
        public static string Settings_PlaySound {
            get {
                return ResourceManager.GetString("Settings_PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Settings_PlaySound_Never {
            get {
                return ResourceManager.GetString("Settings_PlaySound_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When no signal.
        /// </summary>
        public static string Settings_PlaySound_WhenNoSignal {
            get {
                return ResourceManager.GetString("Settings_PlaySound_WhenNoSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With good signal.
        /// </summary>
        public static string Settings_PlaySound_WithGoodSignal {
            get {
                return ResourceManager.GetString("Settings_PlaySound_WithGoodSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System language.
        /// </summary>
        public static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
    }
}
